# Generated by Django 5.1.4 on 2025-04-30 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0012_alter_school_school_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_rounds', models.IntegerField()),
                ('current_round', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('school1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_school1', to='vote.school')),
                ('school2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_school2', to='vote.school')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='vote.school')),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
            },
        ),
    ]
