# Generated by Django 5.1.4 on 2025-04-30 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('vote', '0012_alter_school_school_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='vote.school'),
        ),
    ]
