# Generated by Django 5.1.4 on 2025-05-02 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_winner'),
        ('vote', '0014_remove_school_match_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_tournament_count', models.BigIntegerField(default=0)),
                ('win_match_count', models.BigIntegerField(default=0)),
                ('match_count', models.BigIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.school')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
