# Generated by Django 5.1.4 on 2025-05-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournamentstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentStats',
        ),
    ]
