# Generated by Django 3.2.24 on 2024-02-27 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_image', models.ImageField(null=True, upload_to='static/school_image')),
                ('score', models.IntegerField(default=0)),
                ('voted_users', models.ManyToManyField(related_name='voted_school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
