# Generated by Django 3.2.24 on 2024-02-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_image',
            field=models.ImageField(null=True, upload_to='school_image'),
        ),
    ]
