# Generated by Django 3.2.24 on 2024-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_school_school_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
    ]
