# Generated by Django 3.2.24 on 2024-02-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_school_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_adress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
