# Generated by Django 3.2.24 on 2024-02-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_school_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='score',
        ),
    ]
