# Generated by Django 3.2.24 on 2024-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_remove_school_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_pdf',
            field=models.FileField(null=True, upload_to='school_pdf'),
        ),
    ]
