# Generated by Django 3.2.24 on 2024-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_school_school_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_pdf',
        ),
        migrations.AddField(
            model_name='school',
            name='jungsi_school_pdf',
            field=models.FileField(null=True, upload_to='jungsi_school_pdf'),
        ),
        migrations.AddField(
            model_name='school',
            name='susi_school_pdf',
            field=models.FileField(null=True, upload_to='susi_school_pdf'),
        ),
    ]
