# Generated by Django 5.1.4 on 2025-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20240603_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='voted_users',
        ),
        migrations.AddField(
            model_name='school',
            name='school_score',
            field=models.BigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='School_score',
        ),
    ]
