# Generated by Django 5.1.4 on 2025-01-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_remove_school_voted_users_school_school_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
