# Generated by Django 5.1.4 on 2025-01-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_alter_school_school_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
