# Generated by Django 5.1.4 on 2025-05-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_alter_school_school_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='match_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='win_match_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='win_tournament_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
