# Generated by Django 5.1.4 on 2025-05-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_school_match_count_school_win_match_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='match_count',
        ),
        migrations.RemoveField(
            model_name='school',
            name='win_match_count',
        ),
        migrations.RemoveField(
            model_name='school',
            name='win_tournament_count',
        ),
    ]
