# Generated by Django 5.1.4 on 2025-07-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_school_match_count_school_win_match_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='jungsi_school_pdf',
        ),
        migrations.RemoveField(
            model_name='school',
            name='susi_school_pdf',
        ),
    ]
