# Generated by Django 5.1.4 on 2025-07-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0016_remove_school_jungsi_school_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rank', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.school')),
            ],
            options={
                'unique_together': {('school', 'date')},
            },
        ),
    ]
