# Generated by Django 5.1.4 on 2025-07-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_previousrank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='previousrank',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_score',
        ),
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='school',
            name='rd',
            field=models.FloatField(default=350),
        ),
        migrations.AddField(
            model_name='school',
            name='volatility',
            field=models.FloatField(default=0.06),
        ),
        migrations.AlterField(
            model_name='previousrank',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_image'),
        ),
    ]
