# Generated by Django 3.2.24 on 2024-04-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='github_address',
        ),
    ]
